# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::CustomerInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::CustomerInputType`.

class Types::CustomerInputType
  sig { returns(::String) }
  def email; end

  sig { returns(::String) }
  def first_name; end

  sig { returns(::String) }
  def last_name; end
end
