# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::OrderItemInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::OrderItemInputType`.

class Types::OrderItemInputType
  sig { returns(::String) }
  def product_item; end

  sig { returns(::Integer) }
  def quantity; end
end
