# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::OrderQuestionInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::OrderQuestionInputType`.

class Types::OrderQuestionInputType
  sig { returns(T.nilable(T::Array[::String])) }
  def choices; end

  sig { returns(T.nilable(T::Boolean)) }
  def optional; end

  sig { returns(::String) }
  def prompt; end

  sig { returns(::String) }
  def type; end
end
