# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::OrderQuestionResponseInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::OrderQuestionResponseInputType`.

class Types::OrderQuestionResponseInputType
  sig { returns(T::Hash[::String, T.untyped]) }
  def answer; end

  sig { returns(T.untyped) }
  def question; end
end
