# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `OrderMailer`.
# Please instead update this file by running `bin/tapioca dsl OrderMailer`.

class OrderMailer
  class << self
    sig { params(order: ::Order).returns(::ActionMailer::MessageDelivery) }
    def customer_email(order); end

    sig { params(order: ::Order).returns(::ActionMailer::MessageDelivery) }
    def merchant_email(order); end
  end
end
