import type { ImportsMap, PresetName } from "unplugin-auto-import/types";

export const imports: Array<ImportsMap | PresetName> = [
  "react",
  {
    "@apollo/client": [
      "useApolloClient",
      "useQuery",
      "useLazyQuery",
      "useSubscription",
      "useMutation",
    ],
    "@inertiajs/inertia-react": ["Link", "usePage"],
    "@mantine/core": [
      "packSx",
      "useMantineTheme",
      "useMantineColorScheme",
      "ActionIcon",
      "Alert",
      "Anchor",
      "Badge",
      "Box",
      "Button",
      "Card",
      "Center",
      "Chip",
      "Container",
      "Divider",
      "Group",
      "List",
      "LoadingOverlay",
      "Menu",
      "MediaQuery",
      "Select",
      "Skeleton",
      "Space",
      "Stack",
      "Text",
      "Textarea",
      "TextInput",
      "Title",
      "Tooltip",
      "Transition",
    ],
    "@mantine/form": ["useForm"],
    "@mantine/hooks": [
      "randomId",
      "useDidUpdate",
      "useElementSize",
      "useMediaQuery",
    ],
    "@mantine/notifications": ["showNotification"],
    "@mantine/modals": ["openModal", "closeAllModals"],
    "lodash-es": ["first", "get", "mapKeys", "omit", "pick", "isEmpty"],
    luxon: ["DateTime"],
    "react-use": ["useEvent"],
    "tiny-invariant": [["default", "invariant"]],
    "~/components": ["Head", "ActionBar", "AppLayout", "PageHeader"],
    "~/helpers": [
      "resolve",
      "getMeta",
      "requireMeta",
      "formatError",
      "formatApolloError",
      "useApolloErrorCallback",
      "useDateTime",
      "useMounted",
      "useNestedForm",
      "layoutWithData",
      "usePageErrors",
      "usePageProps",
      "usePageData",
      "useRouter",
      "formErrors",
      "showNotice",
      "showAlert",
    ],
  },
];
